FROM php:8.1-fpm

# Set working directory
WORKDIR /var/www

COPY . .

# Install system dependencies
RUN apt-get update && apt-get install -y \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Install composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
RUN composer self-update

#create new user for composer install
RUN useradd -ms /bin/bash docker

#give permission to user
RUN chown -R docker:docker /var/www

USER docker
