version: "3.7"
services:
    nginx-cobupem-backend:
        container_name: nginx-cobupem-backend
        image: nginx:stable-alpine
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - cobupem-backend
        networks:
            - cobupem-backend-network

    cobupem-backend:
        container_name: cobupem-backend
        build:
            context: ./
            dockerfile: DockerFile
        restart: unless-stopped
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        working_dir: /var/www
        ports:
            - 9000:80
        networks:
            - cobupem-backend-network

networks:
    cobupem-backend-network:
        driver: bridge
